### ISSUE TITLE
Update Readme.md file to include the additions of shields 

### ISSUE THREAD

**Issue by brianreville** [brianreville/OSBookReviewWepApi#12]
Update Readme.md file to include the additions of shields

**Comment by brianreville** [comment]
Hi Lukas
You have been assigned there now

Brian

**Comment by lukasgrabowicz** [comment]
@brianreville Thank you for assigning this task to me. Do you have any specific shields in mind?

**Comment by brianreville** [comment]
@lukasgrabowicz  No bother at all, which ever you think is relevant licence type, passsing build, the CI/CD hasn't been implemented yet or testing so can't do them
