### ISSUE TITLE
Add some info on how to run the project

### ISSUE THREAD

**Issue by jvondermarck** [brianreville/OSBookReviewWepApi#18]
I would be great to have some information on how to install your project locally and how to run your program...

**Comment by jvondermarck** [comment]
I'd add also to talk about 
1. downloading Visual Studio 2022 **PREVIEW** + 
2. create a folder that contains the three different repositories 
3. Open this folder with Visual Studio 2022 Preview
![image](https://user-images.githubusercontent.com/62793491/161441208-d83e5603-0785-42d4-923e-2f9308ed80d0.png)
5. To open run of the three projects, click on the project you want + click on the ".sln" file
![image](https://user-images.githubusercontent.com/62793491/161441244-45d3a28d-c77f-4183-a69c-3151ee81be6d.png)

6. And here you go :)

**Comment by jvondermarck** [comment]
Is that okay for you ? In which file I put these informations ?

**Comment by brianreville** [comment]
@jvondermarck , I think the readme might be the best file for adding this information to
